export interface FilterSection {
  key: string;
  label: string;
  type: "radio" | "checkbox";
  options: { value: string; label: string }[];
}

export const DEFAULT_MEAL_TYPES = [
  "breakfast",
  "dinner",
  "lunch",
  "snack",
  "teatime",
];

export const FILTER_DATA: FilterSection[] = [
  {
    key: "time",
    label: "Cooking Time",
    type: "radio",
    options: [
      { value: "1-10", label: "< 10 mins" },
      { value: "10-25", label: "10 - 25 mins" },
      { value: "25-45", label: "25 - 45 mins" },
      { value: "45-90", label: "45 - 90 mins" },
      { value: "90+", label: "> 90 mins" },
    ],
  },
  {
    key: "ingr",
    label: "Ingredients",
    type: "radio",
    options: [
      { value: "1-5", label: "1 - 5" },
      { value: "5-10", label: "5 - 10" },
      { value: "10-15", label: "10 - 15" },
      { value: "15-20", label: "15 - 20" },
      { value: "20+", label: "> 20" },
    ],
  },
  {
    key: "calories",
    label: "Calories",
    type: "radio",
    options: [
      { value: "0-100", label: "< 100" },
      { value: "100-300", label: "100 - 300" },
      { value: "300-500", label: "300 - 500" },
      { value: "500-700", label: "500 - 700" },
      { value: "700-900", label: "700 - 900" },
      { value: "900-1100", label: "900 - 1100" },
      { value: "1100+", label: "> 1100" },
    ],
  },
  {
    key: "diet",
    label: "Diet",
    type: "checkbox",
    options: [
      { value: "balanced", label: "Balanced" },
      { value: "high-fiber", label: "High Fiber" },
      { value: "high-protein", label: "High Protein" },
      { value: "low-carb", label: "Low Carb" },
      { value: "low-fat", label: "Low Fat" },
      { value: "low-sodium", label: "Low Sodium" },
    ],
  },
  {
    key: "health",
    label: "Health",
    type: "checkbox",
    options: [
      { value: "alcohol-cocktail", label: "Alcohol Cocktail" },
      { value: "alcohol-free", label: "Alcohol Free" },
      { value: "celery-free", label: "Celery Free" },
      { value: "crustacean-free", label: "Crustacean Free" },
      { value: "dairy-free", label: "Dairy Free" },
      { value: "dash", label: "DASH" },
      { value: "egg-free", label: "Egg Free" },
      { value: "fish-free", label: "Fish Free" },
      { value: "fodmap-free", label: "FODMAP Free" },
      { value: "gluten-free", label: "Gluten Free" },
      { value: "immuno-supportive", label: "Immuno Supportive" },
      { value: "keto-friendly", label: "Keto Friendly" },
      { value: "kidney-friendly", label: "Kidney Friendly" },
      { value: "kosher", label: "Kosher" },
      { value: "low-potassium", label: "Low Potassium" },
      { value: "low-sugar", label: "Low Sugar" },
      { value: "lupine-free", label: "Lupine Free" },
      { value: "mediterranean", label: "Mediterranean" },
      { value: "mollusk-free", label: "Mollusk Free" },
      { value: "mustard-free", label: "Mustard Free" },
      { value: "no-oil-added", label: "No Oil Added" },
      { value: "paleo", label: "Paleo" },
      { value: "peanut-free", label: "Peanut Free" },
      { value: "pescatarian", label: "Pescatarian" },
      { value: "pork-free", label: "Pork Free" },
      { value: "red-meat-free", label: "Red Meat Free" },
      { value: "sesame-free", label: "Sesame Free" },
      { value: "shellfish-free", label: "Shellfish Free" },
      { value: "soy-free", label: "Soy Free" },
      { value: "sugar-conscious", label: "Sugar Conscious" },
      { value: "sulfite-free", label: "Sulfite Free" },
      { value: "tree-nut-free", label: "Tree Nut Free" },
      { value: "vegan", label: "Vegan" },
      { value: "vegetarian", label: "Vegetarian" },
      { value: "wheat-free", label: "Wheat Free" },
    ],
  },
  {
    key: "mealType",
    label: "Meal Type",
    type: "checkbox",
    options: [
      { value: "breakfast", label: "Breakfast" },
      { value: "dinner", label: "Dinner" },
      { value: "lunch", label: "Lunch" },
      { value: "snack", label: "Snack" },
      { value: "teatime", label: "Teatime" },
    ],
  },
  {
    key: "dishType",
    label: "Dish Type",
    type: "checkbox",
    options: [
      { value: "alcohol cocktail", label: "Alcohol Cocktail" },
      { value: "biscuits and cookies", label: "Biscuits and Cookies" },
      { value: "bread", label: "Bread" },
      { value: "cereals", label: "Cereals" },
      { value: "condiments and sauces", label: "Condiments and Sauces" },
      { value: "desserts", label: "Desserts" },
      { value: "drinks", label: "Drinks" },
      { value: "egg", label: "Egg" },
      { value: "ice cream and custard", label: "Ice Cream and Custard" },
      { value: "main course", label: "Main Course" },
      { value: "pancake", label: "Pancake" },
      { value: "pasta", label: "Pasta" },
      { value: "pastry", label: "Pastry" },
      { value: "pies and tarts", label: "Pies and Tarts" },
      { value: "pizza", label: "Pizza" },
      { value: "preps", label: "Preps" },
      { value: "preserve", label: "Preserve" },
      { value: "salad", label: "Salad" },
      { value: "sandwiches", label: "Sandwiches" },
      { value: "seafood", label: "Seafood" },
      { value: "soup", label: "Soup" },
      { value: "special occasions", label: "Special Occasions" },
      { value: "starter", label: "Starter" },
      { value: "sweets", label: "Sweets" },
    ],
  },
  {
    key: "cuisineType",
    label: "Cuisine Type",
    type: "checkbox",
    options: [
      { value: "american", label: "American" },
      { value: "asian", label: "Asian" },
      { value: "british", label: "British" },
      { value: "caribbean", label: "Caribbean" },
      { value: "central europe", label: "Central Europe" },
      { value: "chinese", label: "Chinese" },
      { value: "eastern europe", label: "Eastern Europe" },
      { value: "french", label: "French" },
      { value: "greek", label: "Greek" },
      { value: "indian", label: "Indian" },
      { value: "italian", label: "Italian" },
      { value: "japanese", label: "Japanese" },
      { value: "korean", label: "Korean" },
      { value: "kosher", label: "Kosher" },
      { value: "mediterranean", label: "Mediterranean" },
      { value: "mexican", label: "Mexican" },
      { value: "middle eastern", label: "Middle Eastern" },
      { value: "nordic", label: "Nordic" },
      { value: "south american", label: "South American" },
      { value: "south east asian", label: "South East Asian" },
      { value: "world", label: "World" },
    ],
  },
];

export const FILTER_KEYS = [
  ...FILTER_DATA.map((section) => section.key),
  "q",
];

export const HEALTH_TAGS = [
  "vegetarian",
  "vegan",
  "gluten-free",
  "dairy-free",
  "keto-friendly",
  "paleo",
  "kosher",
  "pescatarian",
  "low-sugar",
  "low-fat",
  "low-carb",
  "high-protein",
  "high-fiber",
  "low-sodium",
  "sugar-conscious",
  "no-oil-added",
  "immuno-supportive",
  "mediterranean",
  "dash",
  "egg-free",
  "fish-free",
  "shellfish-free",
  "peanut-free",
  "tree-nut-free",
  "soy-free",
  "wheat-free",
  "red-meat-free",
  "pork-free",
  "fodmap-free",
  "kidney-friendly",
  "low-potassium",
  "alcohol-free",
  "celery-free",
  "crustacean-free",
  "mollusk-free",
  "mustard-free",
  "sesame-free",
  "sulfite-free",
  "lupine-free",
];

export function getTagLabel(tag: string): string {
  return tag
    .replace(/-/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}
